package drools.reglasAseguradora;

import com.keralty.rule.engine.dto.reglasAseguradora.ReglasAseguradoraDTO;
import com.keralty.rule.engine.dto.ExecutionResultDTO;
import java.util.Arrays;


rule "companyInsuranceRule-9991"
when
    ReglasAseguradoraDTO(company == "EPS Sanitas", insuranceID == "9991", result : result)
then
    result.setStatus("SUCCES");
    result.setName("EPS Sanitas");
    result.setInsuranceCode("9991");
    result.setInsuranceType("Entidad Promotora de Salud Contributivo");
end

rule "companyInsuranceRule-PREMIUM"
when
    ReglasAseguradoraDTO(company == "EPS Sanitas", insuranceID == "PREMIUM", result : result)
then
    result.setStatus("SUCCES");
    result.setName("E.P.S Sanitas Plan Premium");
    result.setInsuranceCode("PREMIUM");
    result.setInsuranceType("Entidad Promotora de Salud Contributivo");
end

rule "companyInsuranceRule-900372442-2"
when
    ReglasAseguradoraDTO(company == "EPS Sanitas", insuranceID == "900372442-2", result : result)
then
    result.setStatus("SUCCES");
    result.setName("Salud Total EPS Regimen Subsidiado SAS");
    result.setInsuranceCode("900372442-2");
    result.setInsuranceType("Entidad Promotora de Salud Subsidiado");
end
